### ISSUE TITLE
Plugin installation 

### ISSUE THREAD

**Issue by trewq34** [dm-drogeriemarkt/foreman_vault#19]
Hi,

I'm hoping to get some clarification around the installation, I'm running a RHEL 7.6 box with Foreman 1.19, but having issues getting the plugin to work.

I've followed the instructions, as outlined [here](https://theforeman.org/plugins/#2.3.1RedHatdistributions). The plugin installed fine and is available in one of the dirs in `$GEM_PATH` but when I restart the Foreman services, I get a `Gem loading error: cannot load such file -- foreman_vault (RuntimeError)` error. The full stack trace is:
```
Gem loading error: cannot load such file -- foreman_vault (RuntimeError)
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/output.rb:13:in `strict_err'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:46:in `rescue in block in system_require'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:39:in `block in system_require'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `each'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `system_require'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:19:in `block in system_require'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `each'
  /opt/theforeman/tfm/root/usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
  /usr/share/foreman/config/application.rb:17:in `<top (required)>'
  /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/share/foreman/config/environment.rb:2:in `<top (required)>'
  /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  config.ru:5:in `block in <main>'
  /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
```

It's also worth noting that this is on a corporate network and behind a proxy. The default proxy doesn't allow access to rubygems, I resolve that when doing the `gem install` by switching to a different proxy.

Any help is much appreciated!

Thanks

**Comment by timogoebel** [comment]
Is this an rpm based setup on EL7?
Did you install the plugin in the scl environment?

```bash
scl enable tfm bash
gem install foreman_vault
```

**Comment by trewq34** [comment]
> Is this an rpm based setup on EL7?

Foreman itself is, but foreman_vault isn't

> Did you install the plugin in the scl environment?
> 
> ```shell
> scl enable tfm bash
> gem install foreman_vault
> ```

Yeah I've done it in scl. Do I have to run it as a particular user?

I've also also added `gem 'foreman_vault'` to `~foreman/bundler.d/Gemfile.local.rb`

**Comment by timogoebel** [comment]
@trewq34: I think the best way to solve is to package the plugin as rpm. I've opened a PR for this (https://github.com/theforeman/foreman-packaging/pull/3503). Once it's merged the plugin should be available the next day in the official plugin repo.
