### ISSUE TITLE
Delete certificate only if auth_method is valid

### ISSUE THREAD

**Issue by laugmanuel** [dm-drogeriemarkt/foreman_vault#30]
Deletion of auth_method should only run if the linked `auth_method` is valid and be skipped otherwise.

We could use:
```ruby
      def queue_vault_destroy
        return if !managed? || errors.any?
        return unless auth_method.valid?

        queue.create(name: _('Clear %s Vault data') % self, priority: 60,
                     action: [self, :del_vault])
      end
```
in 
https://github.com/dm-drogeriemarkt/foreman_vault/blob/master/app/models/concerns/foreman_vault/orchestration/vault_policy.rb#L26

**Comment by kamils-iRonin** [comment]
@laugmanuel shouldn't it be `return unless auth_method.valid?` instead of `return unless vault_policy.valid?` in your code snippet?

**Comment by laugmanuel** [comment]
@kamils-iRonin you are absolutely right - I fixed the snippet. In my case the result was the same because both was not valid; but as we only delete the `auth_method` it makes sense to also validate that 👍
